create table if not exists public.daymark_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null,
  goal text not null default 'Improve daily focus',
  working_start text not null default '09:00',
  working_end text not null default '17:00',
  working_days text not null default 'weekdays',
  calendar_connected boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daymark_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  entry_type text not null check (entry_type in ('morning', 'evening')),
  energy integer check (energy between 1 and 5),
  stress integer check (stress between 1 and 5),
  sleep_minutes integer check (sleep_minutes between 0 and 900),
  workload text check (workload in ('light', 'normal', 'heavy')),
  planned_focus_minutes integer check (planned_focus_minutes between 0 and 240),
  productivity integer check (productivity between 1 and 10),
  focused_minutes integer check (focused_minutes between 0 and 240),
  reflection text,
  prediction integer check (prediction between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entry_date, entry_type)
);

create table if not exists public.daymark_priorities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  priority_date date not null,
  title text not null check (char_length(title) between 1 and 180),
  impact text not null default 'MEDIUM IMPACT',
  completed boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_daymark_checkins_user_date on public.daymark_checkins (user_id, entry_date desc);
create index if not exists idx_daymark_priorities_user_date on public.daymark_priorities (user_id, priority_date);

alter table public.daymark_users enable row level security;
alter table public.daymark_checkins enable row level security;
alter table public.daymark_priorities enable row level security;

grant select, insert, update, delete on table public.daymark_users to authenticated;
grant select, insert, update, delete on table public.daymark_checkins to authenticated;
grant select, insert, update, delete on table public.daymark_priorities to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on table public.daymark_users from anon;
revoke all on table public.daymark_checkins from anon;
revoke all on table public.daymark_priorities from anon;

create policy "Users manage their own Daymark profile"
on public.daymark_users for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage their own Daymark checkins"
on public.daymark_checkins for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users manage their own Daymark priorities"
on public.daymark_priorities for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
